apiVersion: v1
kind: Namespace
metadata:
  name: vault-lab

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-jwt-test
  namespace: vault-lab

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent-config
  namespace: vault-lab
data:
  agent.hcl: |
    pid_file = "/tmp/vault-agent.pid"

    vault {
      address = "http://host.minikube.internal:8200"
    }

    auto_auth {
      method "jwt" {
        mount_path = "auth/jwt"

        config = {
          role = "vault-jwt-test"
          path = "/var/run/secrets/tokens/vault-token"
          remove_jwt_after_reading = false          
        }
      }      

      sink "file" {
        config = {
          path = "/tmp/vault-token"
        }
      }
    }

    template {
      source      = "/vault/config/app.ctmpl"
      destination = "/vault/secrets/app.txt"
    }

  app.ctmpl: |
    {{- with secret "secret/data/vault-lab/app" -}}
    username={{ .Data.data.username }}
    password={{ .Data.data.password }}
    {{- end }}

---
apiVersion: v1
kind: Pod
metadata:
  name: vault-jwt-test
  namespace: vault-lab
  labels:
    app: vault-jwt-test

spec:
  serviceAccountName: vault-jwt-test

  containers:
    - name: vault-agent
      image: hashicorp/vault:1.20

      command:
        - vault
        - agent
        - -config=/vault/config/agent.hcl

      volumeMounts:
        - name: vault-agent-config
          mountPath: /vault/config
          readOnly: true

        - name: jwt-token
          mountPath: /var/run/secrets/tokens
          readOnly: true

        - name: vault-secrets
          mountPath: /vault/secrets

  volumes:
    - name: vault-agent-config
      configMap:
        name: vault-agent-config

    - name: jwt-token
      projected:
        sources:
          - serviceAccountToken:
              path: vault-token
              expirationSeconds: 3600
              audience: https://kubernetes.default.svc.cluster.local

    - name: vault-secrets
      emptyDir: {}
